.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SYNAPTIC 8 "Oct  27, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
synaptic
.SH SYNOPSIS
\fB synaptic [ \fB -h ] [\fB -f=filtre-dosyasý ] [\fB -i=baþlangýç-filtresi ]  [\fB -o opsiyon=deðer ]
.br
.SH DESCRIPTION
Synaptic bir apt grafiksel arayüzdür.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
.TP 
 \fB-h 
 yardým metni
.TP
 \fB-f=filtre-dosyasý 
 alternatýif bir filtre dosyasýný kullan
.TP
 \fB-i=baþlangýç-filtre-numarasý 
 numarasý girilen filtreye açýlýþta geç
.TP
 \fB-o opsiyon=deðer
 APT opsiyonlarýný belirler (ileri düzey kullanýcýlar için)
.br
.SH AUTHORS
Bu el kitabý sayfasý Michael Vogt <mvo@debian.org> tarafýndan hazýrlanmýþtýr


