.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SYNAPTIC 8 "Oct  27, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NOME
synaptic
.SH RESUMO
\fB synaptic [ \fB -h ] [\fB -f=arquivo-filtro ] [\fB -i=filtro-inicial ]  [\fB -o option=valor ]
.br
.SH DESCRIÇÃO
Synaptic ié um frontend gráfico para o apt.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPÇÕES
.TP 
 \fB-h 
 exibe texto de ajuda
.TP
 \fB-f=arquivo-filtro
 carrega arquivo de filtro alternativo
.TP
 \fB-i=número-filtro-inicial
 aplica o filtro especificado com o número na inicialização
.TP
 \fB-o option=valor
 define a opção APT ou synaptic diretamente (somente para experts)
.br
.SH AUTORES
Esta página de manual foi escrita por Michael Vogt <mvo@debian.org>,
.SH TRADUÇÃO
Esta página de manual foi traduzido para Português do Brasil por
André Luís Lopes <andrelop@ig.com.br>.

