.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GSYNAPTIC 8 "Nov  14, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NOM
synaptic
.SH SYNOPSIS
\fBgsynaptic\fP [options standard X]
.br
.SH DESCRIPTION
Synaptic est une interface graphique pour apt.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
\fBaucune
.br
.SH AUTEURS
Cette page de manuel a été écrite par Michael Vogt <mvo@debian.org>,
pour le système Debian GNU/Linux (mais peut être utilisée par les autres).
.SH TRADUCTION
Julien Louis <leonptitlouis@ifrance.com>
