.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SYNAPTIC 8 "Oct  27, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
synaptic
.SH SYNOPSIS
\fB synaptic [ \fB -h ] [\fB -f=filter-file ] [\fB -i=initial-filter ]  [\fB -o option=value ]
.br
.SH DESCRIPTION
Synaptic is a graphical frontend for apt.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
.TP 
 \fB-h 
 show help text
.TP
 \fB-f=filter-file 
 load alternative filter file
.TP
 \fB-i=initial-filter-nr 
 apply the filter given with the number on startup
.TP
 \fB-o option=value
 set APT or synaptic option directly (for experts only)
.br
.SH AUTHORS
This manual page was written by Michael Vogt <mvo@debian.org>,


