.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SYNAPTIC 8 "Jun 10, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH "НАЗВАНИЕ"
synaptic \- Графический интерфейс для управления пакетами
.SH "СИНТАКСИС"
\fBsynaptic\fP [опции]
.br
.SH "ОПИСАНИЕ"
Synaptic - это графическая оболочка для APT.  Synaptic в использовании
очень похож на apt-get. Сначала необходимо выполнить команду 'Получить
сведения о пакетах' (Update), которая обновит список пакетов с серверов,
записанных в файле \fIsources.list\fR. На этом шаге не происходит
обновление пакетов, обновляется только информация о доступных пакетах.
После этого можно посмотреть список пакетов, доступных для обновления.
Для этого необходимо активизировать фильтр 'Обновляемые'.
Список пакетов изменится, и останутся отображенными только те пакеты,
для которых доступна новая версия на сервере. Сейчас вы можете
обновить индивидуальные пакеты, выбрав их и нажав маленькую кнопку
`Обновить' слева (либо выполнив двойной щелчок мышью в gtk-версии), или выбрать
для обновления все пакеты, выполнив щелчок по большой кнопке
`Обновить', расположенной вверху. Пока еще никакие пакеты не будут
загружены/обновлены, они всего лишь отмечены для обновления. Возможно,
вы захотите снова сменить фильтр на `Запланированные изменения', чтобы
увидеть что произойдет, если вы будете продолжать обновление. Если вам
нравится то, что вы видите, то нажмите кнопку `Выполнить', и выбранные
пакеты будут загружены и установлены.
.TP
.SH Различие между `Обновить' и  `Обновить дистрибутив'
Различие между `Обновить' (Upgrade) и  `Обновить дистрибутив'
(DistUpgrade) невелико, но очень важно. `Обновить' означает отметить
для обновления пакеты, которые возможно обновить, исключая пакеты с
новыми зависимостями. Ни при каких условиях не будут удалены
установленные пакеты, либо установлены новые.

`Обновить дистрибутив' в добавок к функции `Обновить' также разумно
обрабатывает изменяющиеся зависимости на новые пакеты и использует
интеллектуальную систему разрешения конфликтов при необходимости.

Как правило, вам необходимо будет пользоваться только функцией
`Обновить дистрибутив', если вы выполняете обновление между основными
версиями вашего дистрибутива
(if you upgrade between major versions of your distribution).
.TP
.SH Множественный выбор пакетов
Вы можете выбирать более одного пакета за раз. Для этого необходимо
использовать клавиши SHIFT или CTRL для выбора нескольких пакетов. При
нажатии на кнопку действия (установить/обновить/удалить) для
нескольких пакетов, действие будет выполнено для каждого пакета (как
вы, вероятно, уже догадались (: ).
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics, 
.\" respectively.
.TP
.SH Комбинации клавиш
GTK-версия имеет некторые глобальные комбинации клавиш:
.br
\fBCTRL-k\fR удержать
.br
\fBCTRL-i\fR установить
.br
\fBCTRL-r\fR удалить
.br
\fBCTRL-s\fR искать
.br
\fBCTRL-u\fR обновить
.br
\fBCTRL-p\fR выполнить
.br
\fBCTRL-q\fR выйти

.TP
.SH Фильтры
Synaptic отображает основной список пакетов в соответствии с выбранным
фильтром. Наиболее простым фильтром является, конечно же, `Все
пакеты'. Но существуют и другие фильтры. Вы можете посмотреть
предопределённые фильтры либо сделать собственные нажав на кнопку
`Фильтры' над списком пакетов.

.SH ОПЦИИ
Synaptic распознает стандартные опции X-приложений, а также следующие:
.TP
\fB-f\fR, \fB\-\-filter-file\fR=\fIfilename\fR
задать альтернативный файл фильтров
.TP
\fB-i\fR, \fB\-\-initial-filter\fR=\fIint\fR
начать с фильтром под номером \fIint\fR
.TP
\fB-o\fR, \fB\-\-option\fR=\fIoption\fR
установить опцию synaptic/apt (только для экспертов)

.SH АВТОРЫ
Synaptic был разработан Alfredo K. Kojima
<kojima@conectiva.com.br>. Его последний официальный релиз был
0.16. Michael Vogt <mvo@debian.org> took over his CVS version, where
Alfredo added a nearly complete port to Gtk+. Michael завершил
портирование и добавил несколько новых возможностей.  Видимые
пользователю изменения начиная с этого времени смотрите в файле
\fINEWS\fR. Также в разработке synaptic'а участвует компания
Connectvia. Gustavo Niemeyer <niemeyer@conectiva.com> выполняет
большую часть работы.
.PP
Вся разработка выполняется на http://savannah.gnu.org/projects/synaptic
.PP
Это руководство было написано Wybo Dekker <wybo@servalys.nl> и
Michael Vogt <mvo@debian.org>.
.SH ПЕРЕВОД
Перевод с английского выполнил Святослав Свиридов <svd@altlinux.ru>