.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SYNAPTIC 8 "4 mars 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NOM
synaptic \- Interface graphique pour la gestion des paquets
.SH SYNOPSIS
\fBsynaptic\fP [options]
.br
.SH DESCRIPTION
Synaptic est une interface graphique au système de gestion de paquets apt. Il
permet d'effectuer toutes les actions de la ligne de commande d'apt-get
dans un environnement graphique. Cela inclut l'installation, la mise à niveau,
la mise à niveau inférieur et la suppression d'un paquet et même la mise à
niveau de tout votre système.
.PP
Un manuel avec les instructions détaillées est disponible dans le menu d'aide de
synaptic.

.SH OPTIONS
Synaptic accepte toutes les options standard de la ligne de commande de la boîte
à outils GTK+ ainsi que les suivantes\ :
.TP
\fB-f\fR, \fB\-\-filter-file\fR=\fInomdefichier\fR
spécifie un fichier de filtres alternatif
.TP
\fB-i\fR, \fB\-\-initial-filter\fR=\fInb\fR
applique le filtre numéro \fInb\fR au démarrage
.TP
\fB-o\fR, \fB\-\-option\fR=\fIoption\fR
positionne une option interne (experts seulement)

.SH AUTEURS
Synaptic a été originellement développé par Alfredo K. Kojima
<kojima@conectiva.com.br>. Sa dernière version officielle fut la 0.16. Michael
Vogt <mvo@debian.org> reprit sa version CVS, qui incluait un portage vers Gtk+
presque complet. Michael termina le portage et ajouta quelques fonctionnalités.
Pour voir les changements concernant ce dernier point, regardez le fichier
\fINEWS\fR. Conectiva est toujours impliqué dans le développement de synaptic.
Gustavo Niemeyer <niemeyer@conectiva.com> fait un gros travail.
.PP
Tout le développement est fait sur http://savannah.gnu.org/projects/synaptic
.PP
Cette page de manuel a originellement été écrite par Wybo Dekker
<wybo@servalys.nl> et Michael Vogt <mvo@debian.org> et modifiée par Sebastian
Heinlein <sebastian.heinlein@campus.lmu.de>.

.SH COPYRIGHT
Copyright  (C)  2001-2004 Conectiva S/A
.PP
Copyright  (C)  2002-2004 Michael Vogt
.PP
Il n'y a AUCUNE garantie.
Vous pouvez redistribuer ce logiciel sous les termes de la Licence Publique
Générale GNU. Pour plus d'informations à ce propos, voyez le fichier nommé
COPYING.

.SH TRADUCTION
Richard Bonichon <richard.bonichon@free.fr> et mise à jour par Julien Louis
<leonptitlouis@ifrance.com>.
