

char *transtable[][2] = {
   {"admin",_("System Administration")},
   {"base",_("Base System")},
   {"comm",_("Communication")},
   {"devel",_("Development")},
   {"doc",_("Documentation")},
   {"editors",_("Text Editing")},
   {"electronics",_("Electronics")},
   {"embedded",_("Embedded Devices")},
   {"games",_("Games")},
   {"gnome",_("GNOME Desktop Environment")},
   {"graphics",_("Graphics")},
   {"hamradio",_("Amateur Radio")},
   {"interpreters",_("Computer Languages")},
   {"kde",_("KDE Desktop Environment")},
   {"libdevel",_("Libraries Development")},
   {"libs",_("Libraries")},
   {"mail",_("Email")},
   {"math",_("Mathematics")},
   {"misc",_("Miscellaneous Text Based")},
   {"net",_("Networking")},
   {"news",_("News")},
   {"oldlibs",_("Libraries")},
   {"otherosfs",_("Cross-Platform")},
   {"perl",_("Perl")},
   {"python",_("Python")},
   {"science",_("Science")},
   {"shells",_("Shells")},
   {"sound",_("Multimedia")},
   {"tex",_("Authoring")},
   {"text",_("Word Processing")},
   {"utils",_("Utilities")},
   {"web",_("World Wide Web")},
   {"x11",_("Miscellaneous Graphical")},
   {"non-US",_("non US")},
   {"non-free",_("non free")},
   {"contrib",_("contrib")},

   {NULL, NULL}
};
